[project]
name = "predict-the-introverts-from-the-extroverts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogluon>=1.3.1",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
]
